export const FETCH_LOGIN_INFO = 'FETCH_LOGIN_INFO';
export const FETCH_LOGIN_INFO_SUC = 'FETCH_LOGIN_INFO_SUC';
export const FETCH_LOGIN_INFO_FAI = 'FETCH_LOGIN_INFO_FAI';

export const FETCH_MYMUSIC_INFO = 'FETCH_MYMUSIC_INFO';
export const FETCH_MYMUSIC_INFO_SUC = 'FETCH_MYMUSIC_INFO_SUC';
export const FETCH_MYMUSIC_INFO_FAI = 'FETCH_MYMUSIC_INFO_FAI';


export const FETCH_RECOMMEND_MUSIC_INFO = 'FETCH_RECOMMEND_MUSIC_INFO';
export const FETCH_RECOMMEND_MUSIC_INFO_SUC = 'FETCH_RECOMMEND_MUSIC_INFO_SUC';
export const FETCH_RECOMMEND_MUSIC_INFO_FAI = 'FETCH_RECOMMEND_MUSIC_INFO_FAI';


export const GET_SINGLE_MUSIC_ITEM_ID = 'GET_SINGLE_MUSIC_ITEM_ID';
export const GET_MUTIPLE_MUSIC_ITEM_ID = 'GET_MUTIPLE_MUSIC_ITEM_ID';

export const SINGLE_DELETE_MUSIC_ITEM = 'SINGLE_DELETE_MUSIC_ITEM';
export const MUTIPLE_DELETE_MUSIC_ITEM = 'MUTIPLE_DELETE_MUSIC_ITEM';
export const CHANGE_MUSIC_NAME = 'CHANGE_MUSIC_NAME';

export const SINGLE_CLICK_STATUS = 'SINGLE_CLICK_STATUS';
export const MUTIPLE_CLICK_STATUS = 'MUTIPLE_CLICK_STATUS';
export const CHANGE_MARK_TIME = 'CHANGE_MARK_TIME';